version: '3.9'

services:
  whisper-api:
    image: yaseer/whisper-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env.production
    volumes:
      - ./app_cache:/app/.cache/huggingface
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
